### ISSUE TITLE
Merge "DDL Link Sites" with "Third Party Hosts"

### ISSUE THREAD

**Issue by Igglybuff** [Igglybuff/awesome-piracy#116]
Since they are essentially the same thing.

**Comment by NiceHacksDude** [comment]
If we do this, I suggest we add a Subcategory under DDL Link Sites for Third Party Hosts, since right now Third Party Hosts is a subcategory under streaming, talking specifically about streaming hosts only, yet this is another overlapping issue since sites like Openload, Googledrive, etc, both offer streaming and hosting files, possible may need to change subcategory name to be more specific about this.

**Comment by Aman0307** [comment]
@Igglybuff I would like to contribute to this issue if it is still open.
