### ISSUE TITLE
Sort the List of Contents for easy navigation.

### ISSUE THREAD

**Issue by YaMo97** [Igglybuff/awesome-piracy#43]
Sorting the list of contents will make it easy to browse the file.

Maybe, add the "Hacktoberfest" label to the issue to find contributors.
Read more here: [HacktoberFest by DigitalOcean](https://hacktoberfest.digitalocean.com/)

**Comment by YaMo97** [comment]
Hi, what I meant was ordering the List of Contents in lexicographical/alphabetical order (like in dictionary).

For e.g. - 

This is the List of Contents: - 
>Browser Extensions
Userscripts
Password Vaults
Antivirus
Windows 10 Privacy

So, sorting/ordering it into alphabetical order would result to this: -
>Antivirus
Browser Extensions
Password Vaults
Userscripts
Windows 10 Privacy

This way it'll become easier to find the section, without using search :)

**Comment by Igglybuff** [comment]
I'm not sure how much this adds in functionality. While the ordering of the categories needs updating a little bit, I did make sure to order them in an almost chronological way, i.e. privacy/security stuff _first_ before any of the risky downloading happens.

I'm closing this as I don't think alphabetical order would actually help, but I will make sure to reorder certain parts so that the structure is a little more sensible.
