### ISSUE TITLE
Find information about CreamAPI

### ISSUE THREAD

**Issue by Igglybuff** [Igglybuff/awesome-piracy#80]
For installing Steam DLC

**Comment by PythonTryHard** [comment]
Not sure if qualified for a commit and pull requests but the original thread is https://cs.rin.ru/forum/viewtopic.php?t=70576. Latest version as of time of writing is `v4.1.1.0`, and apparently the user needs to download the DLC first somewhere then use CreamAPI to bypass checks. I'm not sure of the mechanism as I don't use Steam nor CreamAPI.

**Comment by jayk-gupta** [comment]
CreamAPI (CreamInstaller) automatically finds all installed Steam, Epic and Ubisoft games with their respective DLC-related DLL locations on the user's computer, parses SteamCMD, Steam Store and Epic Games Store for user-selected games' DLCs.
Then it provides a straightforward graphical interface utilising the gathered information.

Can add these two links for info about Cream API:
https://github.com/pointfeev/CreamInstaller
https://ruslan.rocks/posts/creamapi

**Comment by anubhav1206** [comment]
CreamAPI is a tool that allows you to bypass DRM protection on games. It is used by some gamers to unlock DLCs and other content that would otherwise require payment. It is important to note that using CreamAPI may be illegal and can result in a ban from the game or platform. The tool works by replacing the original Steam_api.dll file with a modified version that allows the game to run without checking for DRM. The tool is not recommended as it may be illegal and can result in a ban from the game or platform. 

Can I add this? Also where exactly to add?
